version: "3"

services:
  frontend:
    image: sixestates/idp-tutorial-frontend:latest
    ports:
     - '80:80'
    restart: always
    container_name: idp-tutorial-frontend
    environment:
    - API_URL=idp-tutorial-backend:8080

  backend:
    image: sixestates/idp-tutorial-backend:latest
    restart: always
    container_name: idp-tutorial-backend
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "5"
